name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-1"

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform files
        run: terraform fmt

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Apply Terraform changes
        run: terraform plan

      - name: Run terraform plan
        #run: terraform apply -auto-approve # Mahaveer - Don't want to run from Github Action automatically as I have tested it manually , submitting just for assesment
        run: terraform apply

  destroy:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Manual Step - Destroy Infrastructure
        run: terraform destroy
        #run: terraform destroy -auto-approve # Mahaveer - Don't want to run from Github Action automatically as I have tested it manually , submitting just for assesment
